# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SwmmInterface
                                 A QGIS plugin
 User interfaces for EPA SWMM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-08
        copyright            : (C) 2022 by Jubilee Tan
        email                : jubilee2@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SwmmInterface class from file SwmmInterface.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .swmm_interface import SwmmInterface
    return SwmmInterface(iface)
