# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SwmmInterface
                                 A QGIS plugin
 User interfaces for EPA SWMM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-03-08
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Jubilee Tan
        email                : jubilee2@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .swmm_interface_dialog import SwmmInterfaceDialog
from .swmm_interface_base import SwmmInterfaceBase
import os.path


class SwmmInterface(SwmmInterfaceBase):
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        
        super().__init__(iface)
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'SwmmInterface_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.menu = self.tr(u'&Swmm Interface')
        swmm_interface_tool_bar = self.iface.addToolBar(u'Swmm Interface')
        swmm_interface_tool_bar.setObjectName(u'Swmm Interface')
        self.toolbars.append(swmm_interface_tool_bar)
        self.toolbar_dict[''] = swmm_interface_tool_bar
        self.toolbar_dict['swmm_interface'] = swmm_interface_tool_bar

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/swmm_interface/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Link photo to point'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True
